-- 사용자 생성
CREATE USER C##TODO IDENTIFIED BY TODO;
GRANT CONNECT, RESOURCE TO C##TODO;
ALTER USER C##TODO QUOTA UNLIMITED ON USERS;

-- 테이블 생성
DROP TABLE TB_TODO;
CREATE TABLE TB_TODO(
	NO NUMBER PRIMARY KEY,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	DONE CHAR(1) DEFAULT 'N' CHECK(DONE IN ('N', 'Y')),
	REG_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN TB_TODO.NO IS '할 일 번호';
COMMENT ON COLUMN TB_TODO.TITLE IS '제목';
COMMENT ON COLUMN TB_TODO.CONTENT IS '내용';
COMMENT ON COLUMN TB_TODO.DONE IS '완료 여부(Y/N)';
COMMENT ON COLUMN TB_TODO.REG_DATE IS '등록일';

-- 시퀀스 생성
DROP SEQUENCE SEQ_TNO;
CREATE SEQUENCE SEQ_TNO NOCACHE;

-- 샘플 데이터
INSERT INTO TB_TODO
VALUES(SEQ_TNO.NEXTVAL, '테스트1', '테스트1 입니다.', DEFAULT, DEFAULT);

COMMIT;